// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © realKyleYYC

//@version=5
strategy('8FIG BUY/SELL', overlay=true, pyramiding=10,
     default_qty_type=strategy.cash, default_qty_value=7500,
     margin_long=100, margin_short=100,
     initial_capital=25000, currency=currency.USD,
	 backtest_fill_limits_assumption=2, slippage=1,
     commission_type=strategy.commission.cash_per_order, commission_value=2,
     max_lines_count=500, max_labels_count=500, max_boxes_count=500)

//EMA
twenty = ta.ema(close, 20)
fifty = ta.ema(close, 50)
hundred = ta.ema(close, 100)
twohundred = ta.ema(close, 200)
plot(twenty, color=color.new(color.orange, 0), title='20 EMA', linewidth=2)
plot(fifty, color=color.new(color.red, 0), title='50 EMA', linewidth=2)
plot(hundred, color=color.new(color.aqua, 0), title='100 EMA', linewidth=2)
plot(twohundred, color=color.new(color.green, 0), title='200 EMA', linewidth=2)

//RSI
rsiSource = input(title='RSI Source', defval=close)
rsiLength = input(title='RSI Length', defval=14)
rsiValue = ta.rsi(rsiSource, rsiLength)

//BB
length = input.int(77, minval=1, title="Range")
src = ohlc4
mult = input.float(4.2, minval=0.001, maxval=50, title="Range Multiplier")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = 0
p1 = plot(upper, "Upper Range", color=#FFFFFF, offset = offset)
p2 = plot(lower, "Lower Range", color=#FFFFFF, offset = offset)
fill(p1, p2, title = "Range Fill", color=color.rgb(255, 255, 255, 95))

//BUYSELL
dataLong = rsiValue < 20
plotshape(dataLong,title="Buy", text="Buy", location=location.belowbar, style=shape.labelup, size=size.large, color=color.green, textcolor=color.white)

dataShort = rsiValue > 74.2
plotshape(dataShort,title="Sell", text="Sell", location=location.abovebar, style=shape.labeldown, size=size.large, color=color.red, textcolor=color.white)

//WARNINGS
plotshape(rsiValue > 53 and hl2 < twenty,title="SHORT WARNING", text="SHORT WARNING", location=location.abovebar, style=shape.labeldown, size=size.tiny, color=color.red, textcolor=color.white)
plotshape(rsiValue < 47 and hl2 > twenty,title="LONG WARNING", text="LONG WARNING", location=location.belowbar, style=shape.labelup, size=size.tiny, color=color.green, textcolor=color.white)

//SENTIMENT
sentiment = "50/50"
if (rsiValue > 60)
    sentiment := "SHORT"
if (rsiValue > 40 and rsiValue < 60)
    sentiment := "50/50"
if (rsiValue < 40)
    sentiment := "LONG"

//TABLE
tableToggle = input.bool(false,"8FIG TABLE DATA")
if tableToggle == true
    var figTable = table.new(position.middle_right,3,7,color.red,color.yellow,1)
    table.cell(figTable,1,0,"★8FIG★")
    table.cell(figTable,0,1,"BARS"), table.cell(figTable,1,1,"|"),table.cell(figTable,2,1,str.tostring(bar_index + 1))
    table.cell(figTable,0,2,"BIAS"), table.cell(figTable,1,2,"|"),table.cell(figTable,2,2,sentiment)
    table.cell(figTable,0,3,"TICKER"), table.cell(figTable,1,3,"|"),table.cell(figTable,2,3, syminfo.ticker)
    table.cell(figTable,0,4,"HIGH/LOW"), table.cell(figTable,1,4,"|"),table.cell(figTable,2,4,str.tostring(hlcc4))
    table.cell(figTable,0,5,"RSI"), table.cell(figTable,1,5,"|"),table.cell(figTable,2,5,str.tostring(int(rsiValue)))
    table.cell(figTable,0,6,"20 EMA"), table.cell(figTable,1,6,"|"),table.cell(figTable,2,6,"$"+str.tostring(int(twenty)))
